version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: reset_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty123}
      POSTGRES_DB: ${POSTGRES_DB:-reset}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-reset}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prisma-setup:
    image: node:20-alpine
    container_name: reset_prisma_setup
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-qwerty123}@postgres:5432/${POSTGRES_DB:-reset}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty123}
    command: >
      sh -c " apk add --no-cache postgresql-client && npm prune --production=false && npx prisma db push --accept-data-loss && PGPASSWORD=$$POSTGRES_PASSWORD psql -h postgres -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-reset} -f /app/postgres/views_and_udfs.sql "
    depends_on:
      postgres:
        condition: service_healthy

  mongodb:
    image: mongo:7.0
    container_name: reset_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-qwerty123}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-reset_forum}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: reset_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-qwerty123}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-qwerty123}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb

volumes:
  postgres_data:
  mongodb_data:
